<script setup>
import { ref, computed, onMounted, watch } from 'vue'
import { usePersonaActions } from '../composables/usePersonaActions'
import { usePersonaFilter } from '../composables/usePersonaFilter'
import { usePersonaLibrary } from '../composables/usePersonaLibrary'
import { useSimulationPrepare } from '../composables/useSimulationPrepare'
import { usePersonaQuota } from '../composables/usePersonaQuota'
import { useI18n } from 'vue-i18n'
import { useEnvForm } from '../composables/useEnvForm'
import Btn from './ui/Btn.vue'
import Badge from './ui/Badge.vue'
import Kicker from './ui/Kicker.vue'
import Field from './ui/Field.vue'
import Select from './ui/Select.vue'
import QuotaPlanEditor from './step2/QuotaPlanEditor.vue'
import AddPersonaModal from './step2/AddPersonaModal.vue'
import PersonaDetailModal from './step2/PersonaDetailModal.vue'
import PersonaCardGrid from './step2/PersonaCardGrid.vue'
import PersonaLibraryPanel from './step2/PersonaLibraryPanel.vue'
import {
  buildQuotaPlanFromEntries,
} from '../contracts/personaQuotaContract'

const { t } = useI18n()

const props = defineProps({
  simulationId: String,
  projectData: Object,
  graphData: Object,
  systemLogs: Array
})

const emit = defineEmits(['go-back', 'next-step', 'add-log', 'update-status'])

// ----- Model + language picker (useEnvForm — Sub-Slice 37, Refs #203) -----

const {
  ollamaModels,
  presetModels,
  defaultModel,
  ollamaReachable,
  agentToolsEnabled,
  maxToolCallsPerAction,
  loadingModels,
  modelOption,
  customModel,
  language,
  modelOptions,
  loadModels,
  effectiveModel,
} = useEnvForm({ t, onError: (msg) => addLog(msg) })

// ----- Prepare flow (useSimulationPrepare — Sub-Slice 34, Refs #203) -----

const {
  phase,
  isPreparing,
  prepareProgress,
  progressMessage,
  profiles,
  expectedTotal,
  simulationConfig,
  fetchProfilesRealtime,
  startPrepare,
  probeAlreadyPrepared,
} = useSimulationPrepare()

const useCustomRounds = ref(false)
const customMaxRounds = ref(40)
const useCustomDays = ref(false)
const customSimulationDays = ref(3)
const selectedProfile = ref(null)

// Persona review (Slice 2.4): quality badges, approve/reject, inline edit.
// Extracted to usePersonaActions (Sub-Slice 38, Refs #203).
const {
  editingProfile,
  reviewActionPending,
  reviewActionError,
  regenerateHint,
  statusVariant,
  statusLabel,
  issueBadgeVariant,
  startEditingSelected,
  cancelEditing,
  applyProfileToList,
  approveSelected,
  rejectSelected,
  regenerateSelected,
  saveEditingProfile,
  hasRegeneratingPersona,
  personaReview,
} = usePersonaActions({
  simulationId: computed(() => props.simulationId),
  profiles,
  selectedProfile,
  addLog,
})

// Agent-count cap (optional; null = unlimited / all matching entities).
const STORAGE_MAX_AGENTS = 'agora.maxAgents'
const useAgentCap = ref(false)
const maxAgents = ref(Number(localStorage.getItem(STORAGE_MAX_AGENTS)) || 50)
watch(maxAgents, (v) => { localStorage.setItem(STORAGE_MAX_AGENTS, String(v)) })

// ----- Persona-Quota-Plan (Sub-Slice 35: extrahiert nach usePersonaQuota) -----
const {
  useQuotaPlan,
  quotaEntries,
  quotaValidationError,
} = usePersonaQuota({ t })

// ----- Persona-Library + CRUD (usePersonaLibrary — Sub-Slice 39, Refs #203) -----
const {
  personaTemplates, isLoadingPersonaLibrary, personaLibraryError,
  savingPersonaKeys, usingPersonaTemplateIds,
  showAddPersonaModal, newPersona, isSavingPersona,
  profileKey, profilePayload,
  resetNewPersona, submitNewPersona,
  loadPersonaLibrary, savePersona, saveAllPersonas,
  usePersonaTemplate, removePersonaTemplate, removePersona,
} = usePersonaLibrary({
  simulationId: computed(() => props.simulationId),
  profiles,
  fetchProfilesRealtime,
  addLog,
})

// ----- Persona-Filter (usePersonaFilter — Sub-Slice 40, Refs #203) -----
const {
  personaSearch,
  showAllPersonas,
  filteredPersonas,
  visiblePersonas,
} = usePersonaFilter({ profiles })

const autoGeneratedRounds = computed(() => {
  if (!simulationConfig.value?.time_config) return null
  const totalHours = simulationConfig.value.time_config.total_simulation_hours
  const minutesPerRound = simulationConfig.value.time_config.minutes_per_round
  if (!totalHours || !minutesPerRound) return null
  return Math.max(Math.floor((totalHours * 60) / minutesPerRound), 40)
})

const autoGeneratedDays = computed(() => {
  if (!simulationConfig.value?.time_config?.total_simulation_hours) return null
  return Math.max(1, Math.round(simulationConfig.value.time_config.total_simulation_hours / 24))
})

function addLog(msg) { emit('add-log', msg) }

// Guard stores the simId for which refreshQuality was last fired.
// Fired once per sim, triggered by Sim-Wechsel OR first profile arrival.
// Guard prevents re-trigger when profile count changes within the same sim.
const _qualityFetchedForSim = ref(null)

watch(
  () => [props.simulationId, profiles.value.length],
  ([simId, n]) => {
    if (!simId) return                                   // no active sim
    if (n <= 0) return                                   // no profiles yet
    if (_qualityFetchedForSim.value === simId) return    // already fired for this sim
    _qualityFetchedForSim.value = simId                  // set guard before call (race-safe)
    // Fire-and-forget; failures surface via personaReview.error.
    personaReview.refreshQuality(simId)
  },
  { immediate: false },
)

async function triggerPrepare() {
  if (!props.simulationId) {
    addLog(t('errors.unknown') + ': simulationId fehlt')
    emit('update-status', 'error')
    return
  }
  // Quota-Validierung via usePersonaQuota (Sub-Slice 35).
  const payload = {
    simulation_id: props.simulationId,
    use_llm_for_profiles: true,
    parallel_profile_count: 5,
    language: language.value,
  }
  const m = effectiveModel()
  if (m) payload.llm_model = m
  if (useAgentCap.value && maxAgents.value > 0) {
    payload.max_agents = maxAgents.value
  }
  if (useQuotaPlan.value) {
    if (quotaValidationError.value) {
      addLog(`${t('errors.personaGenFailed')}: ${quotaValidationError.value}`)
      emit('update-status', 'error')
      return
    }
    payload.quota_plan = buildQuotaPlanFromEntries(quotaEntries.value)
  }
  await startPrepare({
    payload,
    onLog: addLog,
    onStatusChange: (s) => emit('update-status', s),
  })
}

function handleStart() {
  const params = {}
  if (useCustomRounds.value) params.maxRounds = customMaxRounds.value
  if (useCustomDays.value) params.simulationDays = customSimulationDays.value
  params.simulationId = props.simulationId
  emit('next-step', params)
}

onMounted(() => {
  loadModels()
  loadPersonaLibrary()
  if (props.simulationId) {
    // Probe: if already prepared, hydrate via composable.
    probeAlreadyPrepared(props.simulationId, {
      onLog: addLog,
      onStatusChange: (s) => emit('update-status', s),
    })
  }
})
</script>

<template>
  <div class="step-panel">
    <div class="scroll">

      <!-- Card 0: Setup -->
      <article class="card" :class="{ 'is-active': phase < 1 }">
        <header class="card-head">
          <Kicker num="01">{{ t('step2.title') }}</Kicker>
          <Badge variant="ghost">{{ t('step2.kicker') }}</Badge>
        </header>
        <p class="card-desc">{{ t('step2.sub') }}</p>
        <p v-if="agentToolsEnabled" class="hint warning">
          {{ t('step2.agentTools.warning', { count: maxToolCallsPerAction }) }}
        </p>

        <div class="setup-grid">
          <!-- Model -->
          <div class="setup-cell">
            <Select
              v-model="modelOption"
              :label="t('step2.model.label')"
              :options="modelOptions"
            />
            <p class="hint" v-if="loadingModels">{{ t('step2.model.loadingModels') }}</p>
            <p class="hint" v-else-if="!ollamaReachable">{{ t('step2.model.noOllama') }}</p>
          </div>

          <!-- Custom model input (when 'custom' chosen) -->
          <div class="setup-cell" v-if="modelOption === 'custom'">
            <Field
              v-model="customModel"
              :label="t('step2.model.customLabel')"
              :placeholder="t('step2.model.customPlaceholder')"
            />
          </div>

          <!-- Agent language -->
          <div class="setup-cell">
            <Select
              v-model="language"
              :label="t('step2.language.label')"
              :options="[
                { value: 'de', label: t('step2.language.de') },
                { value: 'en', label: t('step2.language.en') },
              ]"
            />
            <p class="hint">{{ t('step2.language.hint') }}</p>
          </div>

          <!-- Agent cap (optional) -->
          <div class="setup-cell setup-cell--wide">
            <label class="agent-cap">
              <input type="checkbox" v-model="useAgentCap" :disabled="isPreparing" />
              <span>{{ t('step2.agentCap.label') }}</span>
            </label>
            <div v-if="useAgentCap" class="agent-cap-slider">
              <input
                type="range"
                v-model.number="maxAgents"
                min="5"
                max="500"
                step="5"
                :disabled="isPreparing"
              />
              <input
                type="number"
                v-model.number="maxAgents"
                min="1"
                max="2000"
                :disabled="isPreparing"
                class="agent-cap-number"
              />
              <span class="meta">{{ t('step2.agentCap.unit') }}</span>
            </div>
            <p class="hint" v-if="!useAgentCap">{{ t('step2.agentCap.unlimitedHint') }}</p>
          </div>

          <!-- Persona-Quota-Plan (Sub-Slice 20c, 24 / 31): UI in QuotaPlanEditor -->
          <div class="setup-cell setup-cell--wide">
            <QuotaPlanEditor
              v-model:enabled="useQuotaPlan"
              v-model:entries="quotaEntries"
              :disabled="isPreparing"
            />
          </div>
        </div>

        <div class="actions">
          <Btn variant="ghost" @click="$emit('go-back')">← {{ t('common.back') }}</Btn>
          <Btn
            variant="primary"
            arrow
            :disabled="isPreparing"
            :loading="isPreparing && phase < 3"
            @click="triggerPrepare"
          >
            {{ phase === 0 ? t('step2.personas.generate') : t('common.processing') }}
          </Btn>
        </div>
      </article>

      <!-- Card 1: Personas -->
      <article class="card" :class="{ 'is-active': phase === 1 }" v-if="phase >= 1">
        <header class="card-head">
          <Kicker num="02">{{ t('step2.personas.title') }}</Kicker>
          <Badge :variant="phase > 1 ? 'solid' : 'accent'" :dot="phase === 1">
            <template v-if="phase > 1">{{ t('common.completed') }}</template>
            <template v-else>{{ profiles.length }} / {{ expectedTotal || '?' }}</template>
          </Badge>
        </header>
        <p class="card-desc" v-if="phase === 1">
          {{ t('step2.personas.running', { done: profiles.length, total: expectedTotal || '?' }) }}
        </p>

        <div v-if="profiles.length" class="persona-search">
          <input
            v-model="personaSearch"
            type="search"
            class="persona-search-input"
            :placeholder="t('history.search')"
          />
          <span class="meta">
            {{ filteredPersonas.length }} / {{ profiles.length }}
          </span>
        </div>

        <PersonaCardGrid
          :personas="visiblePersonas"
          :saving-persona-keys="savingPersonaKeys"
          :status-variant="statusVariant"
          :status-label="statusLabel"
          :issue-badge-variant="issueBadgeVariant"
          :get-issues-for="personaReview.getIssuesFor"
          :highest-severity-for="personaReview.highestSeverityFor"
          :profile-key="profileKey"
          @select="selectedProfile = $event"
          @remove="removePersona"
          @save="savePersona"
        />

        <div v-if="phase >= 2" class="persona-actions">
          <Btn variant="ghost" @click="showAddPersonaModal = true">+ {{ t('step2.addPersona.title') }}</Btn>
          <Btn variant="ghost" :disabled="!profiles.length" @click="saveAllPersonas">
            {{ t('step2.personas.saveAll') }}
          </Btn>
        </div>
        <PersonaLibraryPanel
          v-if="phase >= 2"
          :templates="personaTemplates"
          :loading="isLoadingPersonaLibrary"
          :error="personaLibraryError"
          :using-ids="usingPersonaTemplateIds"
          @refresh="loadPersonaLibrary"
          @use="usePersonaTemplate"
          @remove="removePersonaTemplate"
        />
        <button
          v-if="filteredPersonas.length > 24 && !showAllPersonas && !personaSearch.trim()"
          class="persona-more-btn"
          @click="showAllPersonas = true"
        >
          + {{ filteredPersonas.length - 24 }} {{ t('common.more') }}
        </button>
        <p v-else-if="!filteredPersonas.length && profiles.length" class="meta">
          {{ t('history.empty') }}
        </p>
      </article>

      <!-- Card 2: Config + start -->
      <article class="card" :class="{ 'is-active': phase >= 2 }" v-if="phase >= 2">
        <header class="card-head">
          <Kicker num="03" accent>{{ t('step3.config.title') }}</Kicker>
          <Badge :variant="phase >= 3 ? 'accent' : 'outline'" :dot="phase === 2">
            {{ phase >= 3 ? t('common.ready') : t('common.processing') }}
          </Badge>
        </header>

        <div class="rounds">
          <label class="rounds-radio">
            <input type="radio" :value="false" v-model="useCustomDays" />
            <span>
              {{ t('step3.config.days') }}: {{ autoGeneratedDays || '?' }}
              <small class="meta">{{ t('step3.config.automatic') }}</small>
            </span>
          </label>
          <label class="rounds-radio">
            <input type="radio" :value="true" v-model="useCustomDays" />
            <span>
              {{ t('step3.config.days') }}:
              <input
                v-model.number="customSimulationDays"
                type="number"
                min="1"
                max="365"
                class="rounds-input"
              />
              <small class="meta">{{ t('step3.config.customValue') }}</small>
            </span>
          </label>
          <label class="rounds-radio">
            <input type="radio" :value="false" v-model="useCustomRounds" />
            <span>
              {{ t('step3.config.rounds') }}: {{ autoGeneratedRounds || '?' }}
              <small class="meta">{{ t('step3.config.automatic') }}</small>
            </span>
          </label>
          <label class="rounds-radio">
            <input type="radio" :value="true" v-model="useCustomRounds" />
            <span>
              {{ t('step3.config.rounds') }}:
              <input
                v-model.number="customMaxRounds"
                type="number"
                min="1"
                max="500"
                class="rounds-input"
              />
              <small class="meta">{{ t('step3.config.customValue') }}</small>
            </span>
          </label>
        </div>

        <div class="actions">
          <Btn
            variant="primary"
            arrow
            :disabled="phase < 3 || hasRegeneratingPersona"
            :title="hasRegeneratingPersona ? t('step2.persona.regeneratingBlock') : undefined"
            @click="handleStart"
          >
            {{ t('step3.controls.start') }}
          </Btn>
        </div>
        <p v-if="hasRegeneratingPersona" class="hint hint--warn">
          {{ t('step2.persona.regeneratingBlock') }}
        </p>
      </article>
    </div>
    <PersonaDetailModal
      :selected-profile="selectedProfile"
      :editing-profile="editingProfile"
      :review-action-pending="reviewActionPending"
      :review-action-error="reviewActionError"
      :regenerate-hint="regenerateHint"
      :review-enabled="personaReview.reviewEnabled.value"
      :status-variant="statusVariant"
      :status-label="statusLabel"
      :issue-badge-variant="issueBadgeVariant"
      :get-issues-for="personaReview.getIssuesFor"
      :highest-severity-for="personaReview.highestSeverityFor"
      @update:selected-profile="selectedProfile = $event"
      @update:editing-profile="editingProfile = $event"
      @update:regenerate-hint="regenerateHint = $event"
      @start-editing="startEditingSelected"
      @cancel-editing="cancelEditing"
      @approve="approveSelected"
      @reject="rejectSelected"
      @regenerate="regenerateSelected"
      @save="saveEditingProfile"
    />
    <AddPersonaModal
      :open="showAddPersonaModal"
      :persona="newPersona"
      :saving="isSavingPersona"
      @update:open="showAddPersonaModal = $event"
      @update:persona="newPersona = $event"
      @submit="submitNewPersona"
    />
  </div>
</template>

<style scoped>
.step-panel {
  height: 100%;
  background: var(--bg);
  display: flex;
  flex-direction: column;
  overflow: hidden;
}
.scroll {
  flex: 1;
  overflow-y: auto;
  padding: var(--s-6);
  display: flex;
  flex-direction: column;
  gap: var(--s-5);
}

.card {
  background: var(--bg);
  border: 1px solid var(--rule);
  border-radius: var(--r-1);
  padding: var(--s-5);
  display: flex;
  flex-direction: column;
  gap: var(--s-4);
}
.card.is-active { border-color: var(--accent); }
.card-head {
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-bottom: 1px solid var(--rule);
  padding-bottom: var(--s-3);
}
.card-desc { color: var(--fg-body); margin: 0; }

.setup-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: var(--s-5) var(--s-7);
}
.setup-cell { display: flex; flex-direction: column; gap: var(--s-2); }
.setup-cell--wide { grid-column: 1 / -1; }

.agent-cap {
  display: flex;
  align-items: center;
  gap: var(--s-2);
  font-family: var(--ff-mono);
  font-size: 12px;
  letter-spacing: var(--ls-mono);
  text-transform: uppercase;
  color: var(--fg);
  cursor: pointer;
}
.agent-cap-slider {
  display: flex;
  align-items: center;
  gap: var(--s-3);
  margin-top: var(--s-2);
}
.agent-cap-slider input[type=range] {
  flex: 1;
  accent-color: var(--accent);
}
.agent-cap-number {
  width: 80px;
  background: transparent;
  border: 0;
  border-bottom: 1px solid var(--rule-strong);
  font-family: var(--ff-mono);
  font-size: var(--fs-16);
  padding: 4px 0;
  color: var(--fg);
  outline: none;
  text-align: right;
}
.agent-cap-number:focus { border-bottom-color: var(--accent); }
.hint {
  font-family: var(--ff-mono);
  font-size: 11px;
  letter-spacing: var(--ls-mono);
  text-transform: uppercase;
  color: var(--fg-muted);
  margin: 0;
}

.actions {
  display: flex;
  gap: var(--s-3);
  justify-content: flex-end;
  border-top: 1px solid var(--rule);
  padding-top: var(--s-4);
}

.persona-actions {
  display: flex;
  gap: var(--s-3);
  justify-content: flex-end;
  border-top: 1px solid var(--rule);
  padding-top: var(--s-3);
}

.rounds {
  display: flex;
  flex-direction: column;
  gap: var(--s-3);
  border-top: 1px solid var(--rule);
  padding-top: var(--s-3);
}
.rounds-radio {
  display: flex;
  align-items: center;
  gap: var(--s-3);
  cursor: pointer;
}
.rounds-input {
  width: 80px;
  background: transparent;
  border: 0;
  border-bottom: 1px solid var(--rule-strong);
  font-family: var(--ff-mono);
  font-size: var(--fs-16);
  padding: 4px 0;
  margin: 0 var(--s-2);
  color: var(--fg);
  outline: none;
}
.rounds-input:focus { border-bottom-color: var(--accent); }

.persona-search {
  display: flex;
  align-items: center;
  gap: var(--s-3);
  border-top: 1px solid var(--rule);
  padding-top: var(--s-3);
}
.persona-search-input {
  flex: 1;
  background: transparent;
  border: 0;
  border-bottom: 1px solid var(--rule-strong);
  padding: var(--s-2) 0;
  font-family: var(--ff-sans);
  font-size: var(--fs-16);
  color: var(--fg);
  outline: none;
}
.persona-search-input:focus { border-bottom-color: var(--accent); }

.persona-more-btn {
  background: transparent;
  border: 1px dashed var(--rule-strong);
  border-radius: var(--r-1);
  padding: var(--s-3);
  font-family: var(--ff-mono);
  font-size: 11px;
  letter-spacing: var(--ls-mono);
  text-transform: uppercase;
  color: var(--fg-muted);
  cursor: pointer;
  transition: border-color 150ms ease, color 150ms ease;
}
.persona-more-btn:hover { color: var(--accent); border-color: var(--accent); }

@media (max-width: 720px) {
  .setup-grid { grid-template-columns: 1fr; }
}

.hint--warn {
  color: var(--warn, #c89020);
}
</style>
