<script setup>
import { ref, computed, onMounted, watch } from 'vue'
import { usePersonaActions } from '../composables/usePersonaActions'
import { usePersonaFilter } from '../composables/usePersonaFilter'
import { usePersonaLibrary } from '../composables/usePersonaLibrary'
import { useSimulationPrepare } from '../composables/useSimulationPrepare'
import { usePersonaQuota } from '../composables/usePersonaQuota'
import { useI18n } from 'vue-i18n'
import { useEnvForm } from '../composables/useEnvForm'
import Btn from './ui/Btn.vue'
import Badge from './ui/Badge.vue'
import Kicker from './ui/Kicker.vue'
import Field from './ui/Field.vue'
import Select from './ui/Select.vue'
import QuotaPlanEditor from './step2/QuotaPlanEditor.vue'
import AddPersonaModal from './step2/AddPersonaModal.vue'
import {
  buildQuotaPlanFromEntries,
} from '../contracts/personaQuotaContract'

const { t } = useI18n()

const props = defineProps({
  simulationId: String,
  projectData: Object,
  graphData: Object,
  systemLogs: Array
})

const emit = defineEmits(['go-back', 'next-step', 'add-log', 'update-status'])

// ----- Model + language picker (useEnvForm — Sub-Slice 37, Refs #203) -----

const {
  ollamaModels,
  presetModels,
  defaultModel,
  ollamaReachable,
  agentToolsEnabled,
  maxToolCallsPerAction,
  loadingModels,
  modelOption,
  customModel,
  language,
  modelOptions,
  loadModels,
  effectiveModel,
} = useEnvForm({ t, onError: (msg) => addLog(msg) })

// ----- Prepare flow (useSimulationPrepare — Sub-Slice 34, Refs #203) -----

const {
  phase,
  isPreparing,
  prepareProgress,
  progressMessage,
  profiles,
  expectedTotal,
  simulationConfig,
  fetchProfilesRealtime,
  startPrepare,
  probeAlreadyPrepared,
} = useSimulationPrepare()

const useCustomRounds = ref(false)
const customMaxRounds = ref(40)
const useCustomDays = ref(false)
const customSimulationDays = ref(3)
const selectedProfile = ref(null)

// Persona review (Slice 2.4): quality badges, approve/reject, inline edit.
// Extracted to usePersonaActions (Sub-Slice 38, Refs #203).
const {
  editingProfile,
  reviewActionPending,
  reviewActionError,
  regenerateHint,
  statusVariant,
  statusLabel,
  issueBadgeVariant,
  startEditingSelected,
  cancelEditing,
  applyProfileToList,
  approveSelected,
  rejectSelected,
  regenerateSelected,
  saveEditingProfile,
  hasRegeneratingPersona,
  personaReview,
} = usePersonaActions({
  simulationId: computed(() => props.simulationId),
  profiles,
  selectedProfile,
  addLog,
})

// Agent-count cap (optional; null = unlimited / all matching entities).
const STORAGE_MAX_AGENTS = 'agora.maxAgents'
const useAgentCap = ref(false)
const maxAgents = ref(Number(localStorage.getItem(STORAGE_MAX_AGENTS)) || 50)
watch(maxAgents, (v) => { localStorage.setItem(STORAGE_MAX_AGENTS, String(v)) })

// ----- Persona-Quota-Plan (Sub-Slice 35: extrahiert nach usePersonaQuota) -----
const {
  useQuotaPlan,
  quotaEntries,
  quotaValidationError,
} = usePersonaQuota({ t })

// ----- Persona-Library + CRUD (usePersonaLibrary — Sub-Slice 39, Refs #203) -----
const {
  personaTemplates, isLoadingPersonaLibrary, personaLibraryError,
  savingPersonaKeys, usingPersonaTemplateIds,
  showAddPersonaModal, newPersona, isSavingPersona,
  profileKey, profilePayload,
  resetNewPersona, submitNewPersona,
  loadPersonaLibrary, savePersona, saveAllPersonas,
  usePersonaTemplate, removePersonaTemplate, removePersona,
} = usePersonaLibrary({
  simulationId: computed(() => props.simulationId),
  profiles,
  fetchProfilesRealtime,
  addLog,
})

// ----- Persona-Filter (usePersonaFilter — Sub-Slice 40, Refs #203) -----
const {
  personaSearch,
  showAllPersonas,
  filteredPersonas,
  visiblePersonas,
} = usePersonaFilter({ profiles })

const autoGeneratedRounds = computed(() => {
  if (!simulationConfig.value?.time_config) return null
  const totalHours = simulationConfig.value.time_config.total_simulation_hours
  const minutesPerRound = simulationConfig.value.time_config.minutes_per_round
  if (!totalHours || !minutesPerRound) return null
  return Math.max(Math.floor((totalHours * 60) / minutesPerRound), 40)
})

const autoGeneratedDays = computed(() => {
  if (!simulationConfig.value?.time_config?.total_simulation_hours) return null
  return Math.max(1, Math.round(simulationConfig.value.time_config.total_simulation_hours / 24))
})

function addLog(msg) { emit('add-log', msg) }

// Guard stores the simId for which refreshQuality was last fired.
// Fired once per sim, triggered by Sim-Wechsel OR first profile arrival.
// Guard prevents re-trigger when profile count changes within the same sim.
const _qualityFetchedForSim = ref(null)

watch(
  () => [props.simulationId, profiles.value.length],
  ([simId, n]) => {
    if (!simId) return                                   // no active sim
    if (n <= 0) return                                   // no profiles yet
    if (_qualityFetchedForSim.value === simId) return    // already fired for this sim
    _qualityFetchedForSim.value = simId                  // set guard before call (race-safe)
    // Fire-and-forget; failures surface via personaReview.error.
    personaReview.refreshQuality(simId)
  },
  { immediate: false },
)

async function triggerPrepare() {
  if (!props.simulationId) {
    addLog(t('errors.unknown') + ': simulationId fehlt')
    emit('update-status', 'error')
    return
  }
  // Quota-Validierung via usePersonaQuota (Sub-Slice 35).
  const payload = {
    simulation_id: props.simulationId,
    use_llm_for_profiles: true,
    parallel_profile_count: 5,
    language: language.value,
  }
  const m = effectiveModel()
  if (m) payload.llm_model = m
  if (useAgentCap.value && maxAgents.value > 0) {
    payload.max_agents = maxAgents.value
  }
  if (useQuotaPlan.value) {
    if (quotaValidationError.value) {
      addLog(`${t('errors.personaGenFailed')}: ${quotaValidationError.value}`)
      emit('update-status', 'error')
      return
    }
    payload.quota_plan = buildQuotaPlanFromEntries(quotaEntries.value)
  }
  await startPrepare({
    payload,
    onLog: addLog,
    onStatusChange: (s) => emit('update-status', s),
  })
}

function handleStart() {
  const params = {}
  if (useCustomRounds.value) params.maxRounds = customMaxRounds.value
  if (useCustomDays.value) params.simulationDays = customSimulationDays.value
  params.simulationId = props.simulationId
  emit('next-step', params)
}

onMounted(() => {
  loadModels()
  loadPersonaLibrary()
  if (props.simulationId) {
    // Probe: if already prepared, hydrate via composable.
    probeAlreadyPrepared(props.simulationId, {
      onLog: addLog,
      onStatusChange: (s) => emit('update-status', s),
    })
  }
})
</script>

<template>
  <div class="step-panel">
    <div class="scroll">

      <!-- Card 0: Setup -->
      <article class="card" :class="{ 'is-active': phase < 1 }">
        <header class="card-head">
          <Kicker num="01">{{ t('step2.title') }}</Kicker>
          <Badge variant="ghost">{{ t('step2.kicker') }}</Badge>
        </header>
        <p class="card-desc">{{ t('step2.sub') }}</p>
        <p v-if="agentToolsEnabled" class="hint warning">
          {{ t('step2.agentTools.warning', { count: maxToolCallsPerAction }) }}
        </p>

        <div class="setup-grid">
          <!-- Model -->
          <div class="setup-cell">
            <Select
              v-model="modelOption"
              :label="t('step2.model.label')"
              :options="modelOptions"
            />
            <p class="hint" v-if="loadingModels">{{ t('step2.model.loadingModels') }}</p>
            <p class="hint" v-else-if="!ollamaReachable">{{ t('step2.model.noOllama') }}</p>
          </div>

          <!-- Custom model input (when 'custom' chosen) -->
          <div class="setup-cell" v-if="modelOption === 'custom'">
            <Field
              v-model="customModel"
              :label="t('step2.model.customLabel')"
              :placeholder="t('step2.model.customPlaceholder')"
            />
          </div>

          <!-- Agent language -->
          <div class="setup-cell">
            <Select
              v-model="language"
              :label="t('step2.language.label')"
              :options="[
                { value: 'de', label: t('step2.language.de') },
                { value: 'en', label: t('step2.language.en') },
              ]"
            />
            <p class="hint">{{ t('step2.language.hint') }}</p>
          </div>

          <!-- Agent cap (optional) -->
          <div class="setup-cell setup-cell--wide">
            <label class="agent-cap">
              <input type="checkbox" v-model="useAgentCap" :disabled="isPreparing" />
              <span>Max. Anzahl Agenten begrenzen</span>
            </label>
            <div v-if="useAgentCap" class="agent-cap-slider">
              <input
                type="range"
                v-model.number="maxAgents"
                min="5"
                max="500"
                step="5"
                :disabled="isPreparing"
              />
              <input
                type="number"
                v-model.number="maxAgents"
                min="1"
                max="2000"
                :disabled="isPreparing"
                class="agent-cap-number"
              />
              <span class="meta">Agenten</span>
            </div>
            <p class="hint" v-if="!useAgentCap">Ohne Begrenzung wird pro Entität im Graph ein Agent erzeugt.</p>
          </div>

          <!-- Persona-Quota-Plan (Sub-Slice 20c, 24 / 31): UI in QuotaPlanEditor -->
          <div class="setup-cell setup-cell--wide">
            <QuotaPlanEditor
              v-model:enabled="useQuotaPlan"
              v-model:entries="quotaEntries"
              :disabled="isPreparing"
            />
          </div>
        </div>

        <div class="actions">
          <Btn variant="ghost" @click="$emit('go-back')">← {{ t('common.back') }}</Btn>
          <Btn
            variant="primary"
            arrow
            :disabled="isPreparing"
            :loading="isPreparing && phase < 3"
            @click="triggerPrepare"
          >
            {{ phase === 0 ? t('step2.personas.generate') : t('common.processing') }}
          </Btn>
        </div>
      </article>

      <!-- Card 1: Personas -->
      <article class="card" :class="{ 'is-active': phase === 1 }" v-if="phase >= 1">
        <header class="card-head">
          <Kicker num="02">{{ t('step2.personas.title') }}</Kicker>
          <Badge :variant="phase > 1 ? 'solid' : 'accent'" :dot="phase === 1">
            <template v-if="phase > 1">{{ t('common.completed') }}</template>
            <template v-else>{{ profiles.length }} / {{ expectedTotal || '?' }}</template>
          </Badge>
        </header>
        <p class="card-desc" v-if="phase === 1">
          {{ t('step2.personas.running', { done: profiles.length, total: expectedTotal || '?' }) }}
        </p>

        <div v-if="profiles.length" class="persona-search">
          <input
            v-model="personaSearch"
            type="search"
            class="persona-search-input"
            :placeholder="t('history.search')"
          />
          <span class="meta">
            {{ filteredPersonas.length }} / {{ profiles.length }}
          </span>
        </div>

        <div class="personas-grid" v-if="visiblePersonas.length">
          <div
            v-for="(p, i) in visiblePersonas"
            :key="p.user_id || i"
            class="persona persona--card"
            :class="{ 'persona--manual': p.is_manual }"
          >
            <button
              class="persona-body"
              type="button"
              @click="selectedProfile = p"
            >
              <span class="persona-name">
                {{ p.name || p.username || 'agent_' + i }}
                <span v-if="p.username && p.name && p.username !== p.name" class="persona-handle">@{{ p.username }}</span>
                <span v-if="p.is_manual" class="persona-tag">manuell</span>
              </span>
              <span class="persona-meta-row">
                <Badge
                  v-if="p.review_status"
                  :variant="statusVariant(p.review_status)"
                  dot
                >{{ statusLabel(p.review_status) }}</Badge>
                <Badge
                  v-if="personaReview.getIssuesFor(p.username).length"
                  :variant="issueBadgeVariant(personaReview.highestSeverityFor(p.username))"
                >{{ personaReview.getIssuesFor(p.username).length }} Hinweis<span v-if="personaReview.getIssuesFor(p.username).length > 1">e</span></Badge>
              </span>
              <span class="persona-bio">{{ (p.bio || '').slice(0, 90) }}{{ (p.bio || '').length > 90 ? '…' : '' }}</span>
              <span v-if="p.interested_topics?.length" class="persona-topics">
                {{ p.interested_topics.slice(0, 3).join(' · ') }}
              </span>
            </button>
            <button
              class="persona-del"
              type="button"
              :title="'Persona löschen'"
              @click.stop="removePersona(p.username)"
            >×</button>
            <button
              class="persona-save"
              type="button"
              :title="t('step2.personas.save')"
              :disabled="savingPersonaKeys.has(profileKey(p))"
              @click.stop="savePersona(p)"
            >↧</button>
          </div>
        </div>

        <div v-if="phase >= 2" class="persona-actions">
          <Btn variant="ghost" @click="showAddPersonaModal = true">+ Persona hinzufügen</Btn>
          <Btn variant="ghost" :disabled="!profiles.length" @click="saveAllPersonas">
            {{ t('step2.personas.saveAll') }}
          </Btn>
        </div>
        <section v-if="phase >= 2" class="persona-library">
          <header class="persona-library-head">
            <div>
              <span class="kicker-mono">{{ t('step2.library.title') }}</span>
              <p class="meta">{{ t('step2.library.hint') }}</p>
            </div>
            <button class="persona-more-btn" type="button" :disabled="isLoadingPersonaLibrary" @click="loadPersonaLibrary">
              {{ t('step2.library.refresh') }}
            </button>
          </header>
          <p v-if="personaLibraryError" class="meta">{{ personaLibraryError }}</p>
          <div v-if="personaTemplates.length" class="persona-library-list">
            <article v-for="template in personaTemplates" :key="template.template_id" class="persona-template">
              <div>
                <strong>{{ template.name || template.username }}</strong>
                <span v-if="template.username" class="persona-handle">@{{ template.username }}</span>
                <p>{{ (template.bio || template.persona || '').slice(0, 120) }}{{ (template.bio || template.persona || '').length > 120 ? '…' : '' }}</p>
              </div>
              <div class="persona-template-actions">
                <button
                  type="button"
                  :disabled="usingPersonaTemplateIds.has(template.template_id)"
                  @click="usePersonaTemplate(template)"
                >
                  {{ t('step2.library.use') }}
                </button>
                <button type="button" @click="removePersonaTemplate(template.template_id)">×</button>
              </div>
            </article>
          </div>
          <p v-else class="meta">{{ t('step2.library.empty') }}</p>
        </section>
        <button
          v-if="filteredPersonas.length > 24 && !showAllPersonas && !personaSearch.trim()"
          class="persona-more-btn"
          @click="showAllPersonas = true"
        >
          + {{ filteredPersonas.length - 24 }} {{ t('common.more') }}
        </button>
        <p v-else-if="!filteredPersonas.length && profiles.length" class="meta">
          {{ t('history.empty') }}
        </p>
      </article>

      <!-- Card 2: Config + start -->
      <article class="card" :class="{ 'is-active': phase >= 2 }" v-if="phase >= 2">
        <header class="card-head">
          <Kicker num="03" accent>{{ t('step3.config.title') }}</Kicker>
          <Badge :variant="phase >= 3 ? 'accent' : 'outline'" :dot="phase === 2">
            {{ phase >= 3 ? t('common.ready') : t('common.processing') }}
          </Badge>
        </header>

        <div class="rounds">
          <label class="rounds-radio">
            <input type="radio" :value="false" v-model="useCustomDays" />
            <span>
              {{ t('step3.config.days') }}: {{ autoGeneratedDays || '?' }}
              <small class="meta">automatisch</small>
            </span>
          </label>
          <label class="rounds-radio">
            <input type="radio" :value="true" v-model="useCustomDays" />
            <span>
              {{ t('step3.config.days') }}:
              <input
                v-model.number="customSimulationDays"
                type="number"
                min="1"
                max="365"
                class="rounds-input"
              />
              <small class="meta">eigener Wert</small>
            </span>
          </label>
          <label class="rounds-radio">
            <input type="radio" :value="false" v-model="useCustomRounds" />
            <span>
              {{ t('step3.config.rounds') }}: {{ autoGeneratedRounds || '?' }}
              <small class="meta">automatisch</small>
            </span>
          </label>
          <label class="rounds-radio">
            <input type="radio" :value="true" v-model="useCustomRounds" />
            <span>
              {{ t('step3.config.rounds') }}:
              <input
                v-model.number="customMaxRounds"
                type="number"
                min="1"
                max="500"
                class="rounds-input"
              />
              <small class="meta">eigener Wert</small>
            </span>
          </label>
        </div>

        <div class="actions">
          <Btn
            variant="primary"
            arrow
            :disabled="phase < 3 || hasRegeneratingPersona"
            :title="hasRegeneratingPersona ? t('step2.persona.regeneratingBlock') : undefined"
            @click="handleStart"
          >
            {{ t('step3.controls.start') }}
          </Btn>
        </div>
        <p v-if="hasRegeneratingPersona" class="hint hint--warn">
          {{ t('step2.persona.regeneratingBlock') }}
        </p>
      </article>
    </div>

    <!-- Modal: persona detail (editorial marginalia layout) -->
    <div v-if="selectedProfile" class="modal" @click.self="selectedProfile = null; cancelEditing()">
      <div class="modal-card">
        <header class="modal-head">
          <div>
            <div class="kicker-mono">№ Persona</div>
            <h3>{{ selectedProfile.name || selectedProfile.username }}</h3>
            <div v-if="selectedProfile.username && selectedProfile.name && selectedProfile.username !== selectedProfile.name" class="modal-handle">@{{ selectedProfile.username }}</div>
          </div>
          <button class="x" @click="selectedProfile = null; cancelEditing()" aria-label="×">×</button>
        </header>

        <div class="review-bar">
          <Badge
            v-if="selectedProfile.review_status"
            :variant="statusVariant(selectedProfile.review_status)"
            dot
          >{{ statusLabel(selectedProfile.review_status) }}</Badge>
          <span v-if="personaReview.reviewEnabled.value" class="meta">Review aktiv</span>
          <span class="review-bar-spacer" />
          <template v-if="!editingProfile">
            <Btn variant="ghost" :disabled="reviewActionPending" @click="startEditingSelected">Bearbeiten</Btn>
            <Btn
              variant="ghost"
              :disabled="reviewActionPending"
              @click="rejectSelected"
            >Ablehnen</Btn>
            <Btn
              variant="ghost"
              :disabled="reviewActionPending"
              :loading="reviewActionPending && selectedProfile?.review_status === 'regenerating'"
              @click="regenerateSelected"
            >{{ t('step2.persona.regenerate') }}</Btn>
            <Btn
              variant="primary"
              :disabled="reviewActionPending"
              @click="approveSelected"
            >Freigeben</Btn>
          </template>
          <template v-else>
            <Btn variant="ghost" :disabled="reviewActionPending" @click="cancelEditing">Abbrechen</Btn>
            <Btn
              variant="primary"
              :loading="reviewActionPending"
              :disabled="reviewActionPending"
              @click="saveEditingProfile"
            >Speichern</Btn>
          </template>
        </div>

        <ul v-if="personaReview.getIssuesFor(selectedProfile.username).length" class="review-issues">
          <li
            v-for="issue in personaReview.getIssuesFor(selectedProfile.username)"
            :key="issue.code"
          >
            <Badge :variant="issueBadgeVariant(issue.severity)">{{ issue.severity }}</Badge>
            <span>{{ issue.code }}</span>
            <span v-if="issue.detail?.missing" class="meta">→ {{ issue.detail.missing.join(', ') }}</span>
          </li>
        </ul>
        <div v-if="!editingProfile" class="regenerate-hint-row">
          <input
            v-model="regenerateHint"
            type="text"
            class="regenerate-hint-input"
            :placeholder="t('step2.persona.regenerateHint')"
            :disabled="reviewActionPending"
          />
        </div>
        <p v-if="reviewActionError" class="meta review-error">{{ reviewActionError }}</p>

        <template v-if="!editingProfile">
          <p class="modal-bio">{{ selectedProfile.bio }}</p>

          <div class="modal-marginalia">
            <dl>
              <div v-if="selectedProfile.age">
                <dt>Alter</dt>
                <dd>{{ selectedProfile.age }}</dd>
              </div>
              <div v-if="selectedProfile.gender">
                <dt>Gender</dt>
                <dd>{{ selectedProfile.gender }}</dd>
              </div>
              <div v-if="selectedProfile.mbti">
                <dt>MBTI</dt>
                <dd class="mono-big">{{ selectedProfile.mbti }}</dd>
              </div>
              <div v-if="selectedProfile.country">
                <dt>Land</dt>
                <dd>{{ selectedProfile.country }}</dd>
              </div>
              <div v-if="selectedProfile.profession">
                <dt>Beruf</dt>
                <dd>{{ selectedProfile.profession }}</dd>
              </div>
            </dl>
            <div class="modal-content">
              <div v-if="selectedProfile.interested_topics?.length" class="topic-chips">
                <span class="kicker-mono">{{ t('step5.agent.interests') }}</span>
                <div class="chips">
                  <span v-for="topic in selectedProfile.interested_topics" :key="topic" class="chip">
                    {{ topic }}
                  </span>
                </div>
              </div>
              <p class="modal-persona" v-if="selectedProfile.persona">
                {{ selectedProfile.persona }}
              </p>
            </div>
          </div>
        </template>

        <div v-else class="form-grid">
          <label class="form-row">
            <span>Anzeigename</span>
            <input v-model="editingProfile.name" type="text" />
          </label>
          <label class="form-row">
            <span>Beruf / Rolle</span>
            <input v-model="editingProfile.profession" type="text" />
          </label>
          <label class="form-row form-row--wide">
            <span>Bio (kurz)</span>
            <input v-model="editingProfile.bio" type="text" maxlength="200" />
          </label>
          <label class="form-row">
            <span>Land</span>
            <input v-model="editingProfile.country" type="text" maxlength="4" />
          </label>
          <label class="form-row">
            <span>Alter</span>
            <input v-model.number="editingProfile.age" type="number" min="15" max="99" />
          </label>
          <label class="form-row">
            <span>Gender</span>
            <select v-model="editingProfile.gender">
              <option value="other">other</option>
              <option value="female">female</option>
              <option value="male">male</option>
            </select>
          </label>
          <label class="form-row">
            <span>MBTI</span>
            <input v-model="editingProfile.mbti" type="text" maxlength="4" />
          </label>
          <label class="form-row form-row--wide">
            <span>Interessen (Komma-getrennt)</span>
            <input v-model="editingProfile.interested_topics" type="text" />
          </label>
          <label class="form-row form-row--wide">
            <span>Persona-Beschreibung</span>
            <textarea v-model="editingProfile.persona" rows="6" />
          </label>
        </div>
      </div>
    </div>

    <AddPersonaModal
      :open="showAddPersonaModal"
      :persona="newPersona"
      :saving="isSavingPersona"
      @update:open="showAddPersonaModal = $event"
      @update:persona="newPersona = $event"
      @submit="submitNewPersona"
    />
  </div>
</template>

<style scoped>
.step-panel {
  height: 100%;
  background: var(--bg);
  display: flex;
  flex-direction: column;
  overflow: hidden;
}
.scroll {
  flex: 1;
  overflow-y: auto;
  padding: var(--s-6);
  display: flex;
  flex-direction: column;
  gap: var(--s-5);
}

.card {
  background: var(--bg);
  border: 1px solid var(--rule);
  border-radius: var(--r-1);
  padding: var(--s-5);
  display: flex;
  flex-direction: column;
  gap: var(--s-4);
}
.card.is-active { border-color: var(--accent); }
.card-head {
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-bottom: 1px solid var(--rule);
  padding-bottom: var(--s-3);
}
.card-desc { color: var(--fg-body); margin: 0; }

.setup-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: var(--s-5) var(--s-7);
}
.setup-cell { display: flex; flex-direction: column; gap: var(--s-2); }
.setup-cell--wide { grid-column: 1 / -1; }

.agent-cap {
  display: flex;
  align-items: center;
  gap: var(--s-2);
  font-family: var(--ff-mono);
  font-size: 12px;
  letter-spacing: var(--ls-mono);
  text-transform: uppercase;
  color: var(--fg);
  cursor: pointer;
}
.agent-cap-slider {
  display: flex;
  align-items: center;
  gap: var(--s-3);
  margin-top: var(--s-2);
}
.agent-cap-slider input[type=range] {
  flex: 1;
  accent-color: var(--accent);
}
.agent-cap-number {
  width: 80px;
  background: transparent;
  border: 0;
  border-bottom: 1px solid var(--rule-strong);
  font-family: var(--ff-mono);
  font-size: var(--fs-16);
  padding: 4px 0;
  color: var(--fg);
  outline: none;
  text-align: right;
}
.agent-cap-number:focus { border-bottom-color: var(--accent); }
.hint {
  font-family: var(--ff-mono);
  font-size: 11px;
  letter-spacing: var(--ls-mono);
  text-transform: uppercase;
  color: var(--fg-muted);
  margin: 0;
}

.actions {
  display: flex;
  gap: var(--s-3);
  justify-content: flex-end;
  border-top: 1px solid var(--rule);
  padding-top: var(--s-4);
}

.personas-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  gap: var(--s-3);
}
.persona {
  border: 1px solid var(--rule);
  background: var(--bg-elevated);
  padding: var(--s-3);
  border-radius: var(--r-1);
  display: flex;
  flex-direction: column;
  gap: var(--s-2);
  text-align: left;
  cursor: pointer;
  transition: background 150ms ease, border-color 150ms ease;
}
.persona:hover { background: var(--bg-panel-2); border-color: var(--rule-strong); }

.persona--card {
  position: relative;
  padding: 0;
  cursor: default;
}
.persona--manual { border-color: var(--accent); }
.persona-body {
  display: flex;
  flex-direction: column;
  gap: var(--s-2);
  padding: var(--s-3);
  background: transparent;
  border: 0;
  text-align: left;
  color: inherit;
  cursor: pointer;
  width: 100%;
}
.persona-del,
.persona-save {
  position: absolute;
  top: 4px;
  width: 22px;
  height: 22px;
  border-radius: 50%;
  border: 1px solid var(--rule);
  background: transparent;
  color: var(--fg-muted);
  font-size: 16px;
  line-height: 1;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
}
.persona-del { right: 6px; }
.persona-save {
  right: 34px;
  font-size: 13px;
}
.persona-del:hover,
.persona-save:hover {
  background: var(--accent);
  color: var(--accent-ink);
  border-color: var(--accent);
}
.persona-meta-row {
  display: flex;
  flex-wrap: wrap;
  gap: var(--s-2);
  margin: var(--s-2) 0;
}
.review-bar {
  display: flex;
  align-items: center;
  gap: var(--s-2);
  flex-wrap: wrap;
  padding: var(--s-3) 0;
  border-bottom: 1px solid var(--rule);
}
.review-bar-spacer { flex: 1; }
.review-issues {
  list-style: none;
  margin: var(--s-3) 0 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: var(--s-2);
}
.review-issues li {
  display: flex;
  align-items: center;
  gap: var(--s-2);
  font-size: var(--font-mono-sm);
  color: var(--fg-body);
}
.review-error {
  color: var(--status-error);
  margin-top: var(--s-2);
}
.persona-tag {
  display: inline-block;
  margin-left: 6px;
  padding: 1px 6px;
  font-size: 9px;
  border-radius: 999px;
  background: var(--accent);
  color: var(--accent-ink);
  letter-spacing: var(--ls-mono);
}
.persona-actions {
  display: flex;
  gap: var(--s-3);
  justify-content: flex-end;
  border-top: 1px solid var(--rule);
  padding-top: var(--s-3);
}

.persona-library {
  border-top: 1px solid var(--rule);
  padding-top: var(--s-3);
  display: flex;
  flex-direction: column;
  gap: var(--s-3);
}
.persona-library-head {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: var(--s-3);
}
.persona-library-list {
  display: grid;
  gap: var(--s-2);
}
.persona-template {
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto;
  gap: var(--s-3);
  border: 1px solid var(--rule);
  border-radius: var(--r-1);
  padding: var(--s-3);
  background: var(--bg-elevated);
}
.persona-template strong {
  font-family: var(--ff-mono);
  font-size: 11px;
  letter-spacing: var(--ls-mono);
  text-transform: uppercase;
}
.persona-template p {
  margin: var(--s-1) 0 0;
  color: var(--fg-body);
}
.persona-template-actions {
  display: flex;
  align-items: center;
  gap: var(--s-2);
}
.persona-template-actions button {
  border: 1px solid var(--rule);
  background: transparent;
  color: var(--fg);
  border-radius: var(--r-1);
  padding: 6px 8px;
  cursor: pointer;
}
.persona-template-actions button:hover {
  border-color: var(--accent);
  color: var(--accent);
}

.persona-name {
  font-family: var(--ff-mono);
  font-size: 11px;
  letter-spacing: var(--ls-mono);
  text-transform: uppercase;
  color: var(--fg-muted);
}
.persona-bio {
  font-family: var(--ff-serif);
  font-size: var(--fs-16);
  line-height: 1.3;
  color: var(--fg);
}

.form-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: var(--s-3);
}
.form-row {
  display: flex;
  flex-direction: column;
  gap: 4px;
  font-family: var(--ff-mono);
  font-size: 11px;
  letter-spacing: var(--ls-mono);
  text-transform: uppercase;
  color: var(--fg-muted);
}
.form-row--wide { grid-column: 1 / -1; }
.form-row input,
.form-row select,
.form-row textarea {
  background: var(--bg-elevated);
  border: 1px solid var(--rule);
  border-radius: var(--r-1);
  color: var(--fg);
  font-family: var(--ff-sans);
  font-size: var(--fs-14);
  padding: 8px 10px;
  text-transform: none;
  letter-spacing: normal;
  outline: none;
}
.form-row textarea { resize: vertical; font-family: var(--ff-serif); line-height: 1.4; }
.form-row input:focus,
.form-row select:focus,
.form-row textarea:focus { border-color: var(--accent); }
@media (max-width: 640px) {
  .form-grid { grid-template-columns: 1fr; }
}

.rounds {
  display: flex;
  flex-direction: column;
  gap: var(--s-3);
  border-top: 1px solid var(--rule);
  padding-top: var(--s-3);
}
.rounds-radio {
  display: flex;
  align-items: center;
  gap: var(--s-3);
  cursor: pointer;
}
.rounds-input {
  width: 80px;
  background: transparent;
  border: 0;
  border-bottom: 1px solid var(--rule-strong);
  font-family: var(--ff-mono);
  font-size: var(--fs-16);
  padding: 4px 0;
  margin: 0 var(--s-2);
  color: var(--fg);
  outline: none;
}
.rounds-input:focus { border-bottom-color: var(--accent); }

.persona-search {
  display: flex;
  align-items: center;
  gap: var(--s-3);
  border-top: 1px solid var(--rule);
  padding-top: var(--s-3);
}
.persona-search-input {
  flex: 1;
  background: transparent;
  border: 0;
  border-bottom: 1px solid var(--rule-strong);
  padding: var(--s-2) 0;
  font-family: var(--ff-sans);
  font-size: var(--fs-16);
  color: var(--fg);
  outline: none;
}
.persona-search-input:focus { border-bottom-color: var(--accent); }

.persona-topics {
  display: block;
  margin-top: var(--s-2);
  font-family: var(--ff-mono);
  font-size: 11px;
  letter-spacing: var(--ls-mono);
  text-transform: uppercase;
  color: var(--accent);
}

.persona-more-btn {
  background: transparent;
  border: 1px dashed var(--rule-strong);
  border-radius: var(--r-1);
  padding: var(--s-3);
  font-family: var(--ff-mono);
  font-size: 11px;
  letter-spacing: var(--ls-mono);
  text-transform: uppercase;
  color: var(--fg-muted);
  cursor: pointer;
  transition: border-color 150ms ease, color 150ms ease;
}
.persona-more-btn:hover { color: var(--accent); border-color: var(--accent); }

.modal {
  position: fixed; inset: 0;
  background: color-mix(in srgb, var(--bg) 60%, transparent);
  display: flex; align-items: center; justify-content: center;
  z-index: 100;
  padding: var(--s-5);
}
.modal-card {
  background: var(--bg);
  border: 1px solid var(--rule-strong);
  padding: var(--s-7);
  max-width: 880px;
  max-height: 85vh;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: var(--s-5);
  border-radius: var(--r-1);
}
.modal-head {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  border-bottom: 1px solid var(--rule);
  padding-bottom: var(--s-3);
}
.kicker-mono {
  font-family: var(--ff-mono);
  font-size: var(--fs-12);
  letter-spacing: var(--ls-mono);
  text-transform: uppercase;
  color: var(--accent);
  margin-bottom: var(--s-2);
}
.modal-head h3 {
  font-family: var(--ff-serif);
  font-weight: 400;
  font-size: clamp(32px, 4vw, 52px);
  line-height: 1.05;
  letter-spacing: -0.02em;
  margin: 0;
  color: var(--fg);
}
.modal-bio {
  font-family: var(--ff-serif);
  font-style: italic;
  font-weight: 400;
  font-size: var(--fs-24);
  line-height: 1.35;
  color: var(--fg-body);
  margin: 0;
  border-left: 2px solid var(--accent);
  padding-left: var(--s-4);
}

.modal-marginalia {
  display: grid;
  grid-template-columns: 160px 1fr;
  gap: var(--s-7);
  border-top: 1px solid var(--rule);
  padding-top: var(--s-5);
}
.modal-marginalia dl {
  display: flex;
  flex-direction: column;
  gap: var(--s-3);
  margin: 0;
}
.modal-marginalia dt {
  font-family: var(--ff-mono);
  font-size: 11px;
  letter-spacing: var(--ls-mono);
  text-transform: uppercase;
  color: var(--fg-muted);
  margin-bottom: 2px;
}
.modal-marginalia dd {
  margin: 0;
  font-family: var(--ff-sans);
  font-size: var(--fs-16);
  color: var(--fg);
}
.modal-marginalia dd.mono-big {
  font-family: var(--ff-mono);
  font-size: var(--fs-20);
  font-weight: 500;
  color: var(--accent);
}
.modal-content {
  display: flex;
  flex-direction: column;
  gap: var(--s-5);
}
.topic-chips { display: flex; flex-direction: column; gap: var(--s-2); }
.topic-chips .chips {
  display: flex;
  flex-wrap: wrap;
  gap: var(--s-2);
}
.topic-chips .chip {
  display: inline-block;
  padding: 4px 10px;
  font-family: var(--ff-mono);
  font-size: 11px;
  letter-spacing: 0.04em;
  border: 1px solid var(--rule-strong);
  background: transparent;
  color: var(--fg);
  border-radius: var(--r-pill);
}
.modal-persona {
  white-space: pre-wrap;
  color: var(--fg-body);
  font-family: var(--ff-sans);
  font-size: var(--fs-16);
  line-height: 1.65;
  margin: 0;
}

@media (max-width: 720px) {
  .modal-marginalia { grid-template-columns: 1fr; }
}
.x {
  background: transparent;
  border: 0;
  font-size: 24px;
  cursor: pointer;
  color: var(--fg-muted);
}
.x:hover { color: var(--accent); }

@media (max-width: 720px) {
  .setup-grid { grid-template-columns: 1fr; }
}

.regenerate-hint-row {
  display: flex;
  align-items: center;
  gap: var(--s-2);
}
.regenerate-hint-input {
  flex: 1;
  background: transparent;
  border: 0;
  border-bottom: 1px solid var(--rule-strong);
  font-family: var(--ff-mono);
  font-size: 12px;
  letter-spacing: 0.04em;
  padding: 4px 0;
  color: var(--fg);
  outline: none;
}
.regenerate-hint-input:focus { border-bottom-color: var(--accent); }
.regenerate-hint-input::placeholder { color: var(--fg-muted); }
.regenerate-hint-input:disabled { opacity: 0.5; cursor: not-allowed; }

.hint--warn {
  color: var(--warn, #c89020);
}
</style>
