/**
 * SimulationStartConfig — extracted from Step2EnvSetup (Issue #586).
 * Prüft: Rendering bei phase >= 2, Start-Button disabled bei phase < 3,
 * Rounds/Days-Radio-Buttons, Start-Event.
 */
import { describe, it, expect } from 'vitest'
import { mount } from '@vue/test-utils'
import { createI18n } from 'vue-i18n'
import SimulationStartConfig from '../SimulationStartConfig.vue'

const localStorageMock = (() => {
  const store: Record<string, string> = {}
  return {
    getItem: (key: string) => store[key] ?? null,
    setItem: (key: string, value: string) => { store[key] = value },
    removeItem: (key: string) => { delete store[key] },
    clear: () => { Object.keys(store).forEach(k => delete store[k]) },
  }
})()
Object.defineProperty(globalThis, 'localStorage', { value: localStorageMock, writable: true })

const i18n = createI18n({
  legacy: false,
  locale: 'de',
  missingWarn: false,
  fallbackWarn: false,
  messages: { de: {}, en: {} },
})

const globalConfig = {
  plugins: [i18n],
  stubs: {
    Button: { template: '<button :disabled="$attrs.disabled" @click="$emit(\'click\')"><slot /></button>' },
    Badge: { template: '<span><slot /></span>' },
    Kicker: { template: '<span><slot /></span>' },
  },
}

function mountComponent(props = {}) {
  return mount(SimulationStartConfig, {
    props: {
      phase: 2,
      useCustomRounds: false,
      customMaxRounds: 40,
      useCustomDays: false,
      customSimulationDays: 3,
      autoGeneratedRounds: 80,
      autoGeneratedDays: 3,
      hasRegeneratingPersona: false,
      ...props,
    },
    global: globalConfig,
  })
}

describe('SimulationStartConfig (Issue #586)', () => {
  it('rendert nicht wenn phase < 2', () => {
    const wrapper = mountComponent({ phase: 1 })
    expect(wrapper.find('.card').exists()).toBe(false)
  })

  it('rendert wenn phase >= 2', () => {
    const wrapper = mountComponent({ phase: 2 })
    expect(wrapper.find('.card').exists()).toBe(true)
  })

  it('Start-Button ist disabled wenn phase < 3', () => {
    const wrapper = mountComponent({ phase: 2 })
    const btn = wrapper.find('button')
    expect(btn.attributes('disabled')).toBeDefined()
  })

  it('Start-Button ist enabled wenn phase >= 3', () => {
    const wrapper = mountComponent({ phase: 3 })
    const btn = wrapper.find('button')
    expect(btn.attributes('disabled')).toBeUndefined()
  })

  it('emittiert start beim Button-Click', async () => {
    const wrapper = mountComponent({ phase: 3 })
    await wrapper.find('button').trigger('click')
    expect(wrapper.emitted('start')).toBeTruthy()
  })

  it('zeigt 4 Radio-Buttons (days auto/custom, rounds auto/custom)', () => {
    const wrapper = mountComponent({ phase: 3 })
    const radios = wrapper.findAll('input[type="radio"]')
    expect(radios).toHaveLength(4)
  })

  it('zeigt hasRegeneratingPersona-Warnung wenn gesetzt', () => {
    const wrapper = mountComponent({ phase: 3, hasRegeneratingPersona: true })
    expect(wrapper.find('p.hint--warn').exists()).toBe(true)
  })
})
