"""Contract-Tests für backend/scripts/normalize_audit_requirements.py.

Regression für den seit 2026-08-03 reproduzierbar roten Step
``Run Python dependency audit`` im Job ``Security scans``: ``uv export``
schreibt ``torch==2.13.0+cpu`` für Linux, und ``pip-audit --strict`` bricht
mit „Dependency not found on PyPI and could not be audited“ ab, weil PyPI
keine Local-Version-Labels führt.

Aufrufe via subprocess.run — wir testen den CLI-Vertrag, nicht Internals.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
SCRIPT_PATH = _REPO_ROOT / "backend" / "scripts" / "normalize_audit_requirements.py"

# Wortlaut aus dem echten ``uv export --frozen --no-dev --no-hashes
# --no-emit-project``-Output (Stand backend/uv.lock @ 4db7016b).
_EXPORT_EXCERPT = """\
# This file was autogenerated by uv via the following command:
#    uv export --frozen --no-dev --no-hashes --no-emit-project
flask==3.1.2
torch==2.13.0 ; sys_platform != 'linux'
torch==2.13.0+cpu ; sys_platform == 'linux'
nltk==3.10.1
"""


def _run(source: Path, target: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPT_PATH), str(source), str(target)],
        capture_output=True,
        text=True,
        check=False,
    )


def test_strips_local_version_but_keeps_marker(tmp_path):
    source = tmp_path / "req.txt"
    target = tmp_path / "req.norm.txt"
    source.write_text(_EXPORT_EXCERPT, encoding="utf-8")

    result = _run(source, target)

    assert result.returncode == 0, result.stderr
    lines = target.read_text(encoding="utf-8").splitlines()
    assert "torch==2.13.0 ; sys_platform == 'linux'" in lines
    # Kein einziges Local-Version-Label darf uebrig bleiben, sonst faellt
    # pip-audit --strict wieder ueber die PyPI-Aufloesung.
    assert not [line for line in lines if "+cpu" in line]


def test_leaves_untouched_lines_byte_identical(tmp_path):
    source = tmp_path / "req.txt"
    target = tmp_path / "req.norm.txt"
    source.write_text(_EXPORT_EXCERPT, encoding="utf-8")

    _run(source, target)

    original = _EXPORT_EXCERPT.splitlines()
    normalized = target.read_text(encoding="utf-8").splitlines()
    assert len(normalized) == len(original)
    for before, after in zip(original, normalized, strict=True):
        if "+cpu" not in before:
            assert after == before


def test_handles_comments_index_directives_and_blank_lines(tmp_path):
    source = tmp_path / "req.txt"
    target = tmp_path / "req.norm.txt"
    source.write_text(
        "--extra-index-url https://download.pytorch.org/whl/cpu\n"
        "\n"
        "# torch==9.9.9+cpu steht nur im Kommentar\n"
        "torchvision==0.24.0+cpu ; sys_platform == 'linux'\n",
        encoding="utf-8",
    )

    result = _run(source, target)

    assert result.returncode == 0, result.stderr
    lines = target.read_text(encoding="utf-8").splitlines()
    assert lines[0] == "--extra-index-url https://download.pytorch.org/whl/cpu"
    assert lines[1] == ""
    assert lines[2] == "# torch==9.9.9+cpu steht nur im Kommentar"
    assert lines[3] == "torchvision==0.24.0 ; sys_platform == 'linux'"


def test_missing_source_exits_2(tmp_path):
    result = _run(tmp_path / "does-not-exist.txt", tmp_path / "out.txt")

    assert result.returncode == 2
    assert "Eingabe nicht lesbar" in result.stderr
