<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import Button from '@/components/v4/forms/Button.vue'
import Badge from '../ui/Badge.vue'
import Kicker from '@/components/v4/data/Kicker.vue'

const { t } = useI18n()

defineProps({
  phase: { type: Number, required: true },
  useCustomRounds: { type: Boolean, required: true },
  customMaxRounds: { type: Number, required: true },
  useCustomDays: { type: Boolean, required: true },
  customSimulationDays: { type: Number, required: true },
  autoGeneratedRounds: { type: [Number, null], default: null },
  autoGeneratedDays: { type: [Number, null], default: null },
  hasRegeneratingPersona: { type: Boolean, default: false },
})

const emit = defineEmits([
  'update:useCustomRounds',
  'update:customMaxRounds',
  'update:useCustomDays',
  'update:customSimulationDays',
  'start',
])
</script>

<template>
  <article class="card" :class="{ 'is-active': phase >= 2 }" v-if="phase >= 2">
    <header class="card-head">
      <Kicker num="03" accent>{{ t('step3.config.title') }}</Kicker>
      <Badge :variant="phase >= 3 ? 'accent' : 'outline'" :dot="phase === 2">
        {{ phase >= 3 ? t('common.ready') : t('common.processing') }}
      </Badge>
    </header>

    <div class="rounds">
      <label class="rounds-radio">
        <input type="radio" :value="false" :checked="!useCustomDays" @change="emit('update:useCustomDays', false)" />
        <span>
          {{ t('step3.config.days') }}: {{ autoGeneratedDays || '?' }}
          <small class="meta">{{ t('step3.config.automatic') }}</small>
        </span>
      </label>
      <label class="rounds-radio">
        <input type="radio" :value="true" :checked="useCustomDays" @change="emit('update:useCustomDays', true)" />
        <span>
          {{ t('step3.config.days') }}:
          <input
            :value="customSimulationDays"
            type="number"
            min="1"
            max="365"
            class="rounds-input"
            @input="emit('update:customSimulationDays', Number(($event.target as HTMLInputElement).value))"
          />
          <small class="meta">{{ t('step3.config.customValue') }}</small>
        </span>
      </label>
      <label class="rounds-radio">
        <input type="radio" :value="false" :checked="!useCustomRounds" @change="emit('update:useCustomRounds', false)" />
        <span>
          {{ t('step3.config.rounds') }}: {{ autoGeneratedRounds || '?' }}
          <small class="meta">{{ t('step3.config.automatic') }}</small>
        </span>
      </label>
      <label class="rounds-radio">
        <input type="radio" :value="true" :checked="useCustomRounds" @change="emit('update:useCustomRounds', true)" />
        <span>
          {{ t('step3.config.rounds') }}:
          <input
            :value="customMaxRounds"
            type="number"
            min="1"
            max="500"
            class="rounds-input"
            @input="emit('update:customMaxRounds', Number(($event.target as HTMLInputElement).value))"
          />
          <small class="meta">{{ t('step3.config.customValue') }}</small>
        </span>
      </label>
    </div>

    <div class="actions">
      <Button
        variant="primary"
        arrow
        :disabled="phase < 3 || hasRegeneratingPersona"
        :title="hasRegeneratingPersona ? t('step2.persona.regeneratingBlock') : undefined"
        @click="emit('start')"
      >
        {{ t('step3.controls.start') }}
      </Button>
    </div>
    <p v-if="hasRegeneratingPersona" class="hint hint--warn">
      {{ t('step2.persona.regeneratingBlock') }}
    </p>
  </article>
</template>

<style scoped>
.card {
  background: var(--bg);
  border: 1px solid var(--rule);
  border-radius: var(--r-1);
  padding: var(--s-5);
  display: flex;
  flex-direction: column;
  gap: var(--s-4);
}
.card.is-active { border-color: var(--accent); }
.card-head {
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-bottom: 1px solid var(--rule);
  padding-bottom: var(--s-3);
}

.rounds {
  display: flex;
  flex-direction: column;
  gap: var(--s-3);
  border-top: 1px solid var(--rule);
  padding-top: var(--s-3);
}
.rounds-radio {
  display: flex;
  align-items: center;
  gap: var(--s-3);
  cursor: pointer;
}
.rounds-input {
  width: 80px;
  background: transparent;
  border: 0;
  border-bottom: 1px solid var(--rule-strong);
  font-family: var(--ff-mono);
  font-size: var(--fs-16);
  padding: 4px 0;
  margin: 0 var(--s-2);
  color: var(--fg);
  outline: none;
}
.rounds-input:focus { border-bottom-color: var(--accent); }

.actions {
  display: flex;
  gap: var(--s-3);
  justify-content: flex-end;
  border-top: 1px solid var(--rule);
  padding-top: var(--s-4);
}

.hint {
  font-family: var(--ff-mono);
  font-size: 11px;
  letter-spacing: var(--ls-mono);
  text-transform: uppercase;
  color: var(--fg-muted);
  margin: 0;
}
.hint--warn {
  color: var(--warn);
}

.meta {
  color: var(--text-secondary);
  font-family: var(--font-sans);
  letter-spacing: 0;
  text-transform: none;
}
.card {
  background: var(--surface-elevated);
  border-color: var(--hairline);
  border-radius: var(--r-7);
  box-shadow: var(--shadow-1);
}
.card.is-active {
  border-color: var(--accent);
  box-shadow: 0 0 0 1px var(--accent-tint-bg), var(--shadow-1);
}
.card-head,
.rounds {
  border-color: var(--separator);
}
.rounds-input {
  background: var(--surface-elevated);
  border: 1px solid var(--hairline);
  border-radius: var(--r-5);
  color: var(--text-primary);
  font-family: var(--font-sans);
  letter-spacing: 0;
  padding: 7px 10px;
}
.rounds-input:focus {
  border-color: var(--accent);
  box-shadow: 0 0 0 3px var(--focus-ring);
}
</style>
