/**
 * Wichtigste Einstiegsseiten zuerst, dann Gruppen/Rest, datierte Protokolle chronologisch am Ende.
 * Statische Seitenreihenfolge ( numerische Präfixe wie 2026-… kollidieren sonst
 * als Sidebar-Order → BLUME_DUPLICATE_SIDEBAR_ORDER ). Neue Dateien erscheinen
 * automatisch nach den hier gelisteten.
 */
export default {
  pages: [
    "architecture",
    "STATUS",
    "api",
    "api-contracts",
    "operator-guide",
    "operations",
    "configuration",
    "auth",
    "glossary",
    "security-hardening",
    "agent-tools",
    "analytics",
    "release-process",
    "backup-restore",
    "agents",
    "archive",
    "assets",
    "AUDIT_REPORT_MAY_2026",
    "audit-followup-issues",
    "audits",
    "ci-e2e-audit",
    "ci-egress-allowlist",
    "decisions",
    "dependency-risk-register",
    "deployment",
    "deployment-dev",
    "deployment-prod-like",
    "design",
    "design-reference",
    "diagrams",
    "embedding-provider-switch",
    "epics",
    "graphrag-speedup",
    "HANDOVER-2026-07-05",
    "index",
    "media",
    "paper",
    "plans",
    "provider-runtime-settings",
    "README",
    "reference-runs",
    "runbooks",
    "sbom-provenance",
    "secret-key-lifecycle",
    "security-threat-model",
    "session-2026-07-18-docker-debug",
    "superpowers",
    "test-seeds",
    "testing",
    "tooling",
    "troubleshooting",
    "ui",
    "worklogs",
    "05-19-pytest-cve-tracking-arbeitsprotokoll",
    "07-10-onboarding-provider-unification-slice-1-arbeitsprotokoll",
    "07-18-lessons-learned-provider-key-routing",
    "07-18-sim-agenten-stumm-arbeitsprotokoll",
    "07-31-issue-772-cve-basisimage-research"
  ],
};
